<script lang="ts">
  import { onMount } from 'svelte';
  import { writable } from 'svelte/store';

  import type { Headings } from '@lib/metagg';

  export let isDev = false;
  /** Value automatically generated by astro. */
  export let headings: Headings[] = [];
  /** Interval between updates.
   * Too low and it causes lag.
   * Too high and it may impact performance.
   */
  export let frameRate = 20;

  export let decisionOffset = 20;

  export let sidebarId = '';
  export let sidebarButtonId = '';

  export let largeWidth = 900;

  const sidebar = document.getElementById(sidebarId);
  const closeable = window.innerWidth < largeWidth;
  const sidebarButton = document.getElementById(sidebarButtonId);

  function closeSidebar() {
    if (sidebar != null) {
      sidebar.style.display = 'none';
    }
    if (sidebarButton?.style.display === 'none') {
      sidebarButton.style.display = '';
    }
  }

  /** Index of selected headings. */
  const activeIndex = writable(0);
  /** An array of elements of the heading.
   * If the element is not found, it isn't added to the array.
   */
  const headingElements = headings.flatMap((heading) => document.getElementById(heading.slug) || []);

  /* 
    Even if these don't match, most likely work correctly.
    Will output logs for maintainability.
  */
  if (isDev && headings.length !== headingElements.length) {
    let messageLines = [
      'Incorrect headings detected.',
      `Received headings: ${headings.length}`,
      `Detected headings: ${headingElements.length}`,
    ];
    console.error(`[HeadingList] ${messageLines.join('\n')}`);
  }

  /** This function applies the heading index update.
   * Maybe there is a better way.
   *
   * `$activeIndex` <= `$activePosition` < `$activeIndex + 1`
   */
  function setIndex(position: number) {
    position += decisionOffset;

    if (headingElements[$activeIndex + 1] && position >= headingElements[$activeIndex + 1].offsetTop) {
      for (; $activeIndex < headingElements.length - 1; $activeIndex++) {
        if (position < headingElements[$activeIndex + 1].offsetTop) {
          break;
        }
      }
    } else if (position < headingElements[$activeIndex].offsetTop) {
      for (; $activeIndex > 0; $activeIndex--) {
        if (position >= headingElements[$activeIndex].offsetTop) {
          break;
        }
      }
    }
  }

  /** Update active heading
   * Using scroll events is responsive, but it may impact performance.
   *
   * https://developer.mozilla.org/docs/Web/API/Document/scroll_event
   */
  const interval = setInterval(() => setIndex(window.scrollY), 1000 / frameRate);
  onMount(() => {
    return () => clearInterval(interval);
  });
</script>

{#if closeable}
  <div data-sidebar-buttons>
    <button
      on:click={() => {
        closeable && closeSidebar();
      }}>Close Sidebar</button
    >
    <button
      on:click={() => {
        if (!closeable) {
          return;
        }
        window.scroll(0, 0);
        closeSidebar();
      }}
    >
      Close and Top
    </button>
  </div>
{/if}
<ul>
  {#each headings as heading, i}
    <li data-heading-depth={heading.depth} data-heading-status={i === $activeIndex ? 'active' : 'inactive'}>
      <a
        on:click={() => {
          closeable && closeSidebar();
        }}
        href={`#${heading.slug}`}>{heading.text}</a
      >
    </li>
  {/each}
</ul>

<style lang="stylus">
  @import "../../styles/api.styl"

  [data-sidebar-buttons]
    flex(column, 0.75rem)

  button
    background none
    sans(1rem)
    border 1px solid var(--border)
    border-radius 8px

  ul
    list-style none
    flex(column, 0.25rem)

    li
      a
        box-sizing border-box
        display block
        height 100%
        width 100%
        text-decoration none

        padding 0.25rem 0.5rem
        sans(1rem)
        @media screen and (min-width widths.largest)
          padding 0.5rem 0.75rem
          sans(1.125rem)

      &[data-heading-status="inactive"]
        border-left 1px solid rgba(gray, 0.5)

        &:hover
          background-color rgba(gray, 0.25)

      &[data-heading-status="active"]
        background-color var(--link-background-hover)
        border-radius 0 8px 8px 0
        border-left 1px solid var(--link)

      &[data-heading-depth="2"]
        font-weight 700

      &[data-heading-depth="3"]
        font-weight 400
</style>
