<script lang="ts">
  import { onMount } from 'svelte';
  import { writable } from 'svelte/store';

  import type { Headings } from '@lib/metagg';

  export let isDev = false;
  /** Value automatically generated by astro. */
  export let headings: Headings[] = [];
  /** Interval between updates.
   * Too low and it causes lag.
   * Too high and it may impact performance.
   */
  export let frameRate = 20;

  /** Index of selected headings. */
  const activeIndex = writable(0);
  /** An array of elements of the heading.
   * If the element is not found, it isn't added to the array.
   */
  const headingElements = headings.flatMap((heading) => document.getElementById(heading.slug) || []);

  /* 
    Even if these don't match, most likely work correctly.
    Will output logs for maintainability.
  */
  if (isDev && headings.length !== headingElements.length) {
    let messageLines = [
      'Incorrect headings detected.',
      `Received headings: ${headings.length}`,
      `Detected headings: ${headingElements.length}`,
    ];
    console.error(`[HeadingList] ${messageLines.join('\n')}`);
  }

  /** This function applies the heading index update.
   * Maybe there is a better way.
   *
   * `$activeIndex` <= `$activePosition` < `$activeIndex + 1`
   */
  function setIndex(position: number) {
    if (headingElements[$activeIndex + 1] && position >= headingElements[$activeIndex + 1].offsetTop) {
      for (; $activeIndex < headingElements.length - 1; $activeIndex++) {
        if (position < headingElements[$activeIndex + 1].offsetTop) {
          break;
        }
      }
    } else if (position < headingElements[$activeIndex].offsetTop) {
      for (; $activeIndex > 0; $activeIndex--) {
        if (position >= headingElements[$activeIndex].offsetTop) {
          break;
        }
      }
    }
  }

  /** Update active heading
   * Using scroll events is responsive, but it may impact performance.
   *
   * https://developer.mozilla.org/docs/Web/API/Document/scroll_event
   */
  const interval = setInterval(() => setIndex(window.scrollY), 1000 / frameRate);
  onMount(() => {
    return () => clearInterval(interval);
  });
</script>

<ul>
  {#each headings as heading, i}
    <li data-heading-depth={heading.depth} data-heading-status={i === $activeIndex ? 'active' : 'inactive'}>
      <a href={`#${heading.slug}`}>{heading.text}</a>
    </li>
  {/each}
</ul>

<style lang="stylus">
  @import "../../styles/api.styl"

  ul
    list-style none
    flex(column, 0.25rem)

    li
      padding 0.25rem 0.5rem
      sans(1rem)
      @media screen and (min-width widths.largest)
        padding 0.5rem 0.75rem
        sans(1.125rem)

      &[data-heading-status="active"]
        font-weight 700
        background linear-gradient(45deg, rgba(64, 0, 255, .2), rgba(255, 0, 64, .2))
        border-radius 0 8px 8px 0
        border-left 8px solid var(--link)

        &[data-heading-depth="3"]
          border-left 4px solid var(--link)

      a
        text-decoration none
        &:hover
          text-decoration underline
</style>
